---
- name: Install Pulsar
  hosts: pulsar_nodes
  become: true
  vars_files: vault_staging.yml
  vars:
    # Pulsar system user and group
    pulsar_user: pulsar
    pulsar_group: pulsar
    # Installation directory for Pulsar
    pulsar_install_dir: /opt/pulsar
    # Path to Python virtual environment
    venv_path: "{{ pulsar_install_dir }}/venv"
    # Whether to install Pulsar with web components
    install_web_components: true # Set to false if you don't need web mode initially
    # Enable message queue support
    mq: true # Set to true if message queue support is required

  tasks:
    # Ensure Python and pip are installed (using DNF)
    - name: Ensure required packages are installed for Python and venv (DNF)
      dnf:
        name:
          - python3
          - python3-pip # While venv usually includes pip, it's good to ensure it's present
        state: present
        update_cache: true

    # Create Pulsar group
    - name: Create Pulsar user and group
      group:
        name: "{{ pulsar_group }}"
        state: present
      register: pulsar_group_result

    # Create Pulsar user (only if group was changed/created)
    - name: Create Pulsar user
      user:
        name: "{{ pulsar_user }}"
        group: "{{ pulsar_group }}"
        home: "{{ pulsar_install_dir }}"
        create_home: true
        state: present
      when: pulsar_group_result.changed

    # Create installation directory for Pulsar
    - name: Create Pulsar install directory
      file:
        path: "{{ pulsar_install_dir }}"
        state: directory
        owner: "{{ pulsar_user }}"
        group: "{{ pulsar_group }}"
        mode: '0755'

    # Create Python virtual environment for Pulsar
    - name: Create Python virtual environment
      command:
        cmd: "python3 -m venv {{ venv_path }}"
      become_user: "{{ pulsar_user }}"
      args:
        chdir: "{{ pulsar_install_dir }}"
      register: create_venv_result
      ignore_errors: yes # Allow if venv already exists

    # Install Pulsar (with or without web components)
    - name: Install Pulsar
      pip:
        name: "pulsar-app{{ '[web]' if install_web_components else '' }}"
        virtualenv: "{{ venv_path }}"
      become_user: "{{ pulsar_user }}"

    # Install kombu if message queue is enabled
    - name: Install kombu if mq is true
      pip:
        name: kombu
        virtualenv: "{{ venv_path }}"
      become_user: "{{ pulsar_user }}"
      when: mq

    # Install pycurl if message queue is enabled
    - name: Install pycurl if mq is true
      pip:
        name: pycurl
        virtualenv: "{{ venv_path }}"
      become_user: "{{ pulsar_user }}"
      when: mq

    # Generate Pulsar configuration files (only if venv was just created or config doesn't exist)
    - name: Create Pulsar configuration files
      command:
       cmd: "{{ venv_path }}/bin/pulsar-config --mq"
      become_user: "{{ pulsar_user }}"
      args:
        chdir: "{{ pulsar_install_dir }}"
      when: create_venv_result.changed or not (lookup('file', '{{ pulsar_install_dir }}/server.ini') | length > 0)
      ignore_errors: yes  # If the file is already in place, continue

    # Create log directory for Pulsar
    - name: Create Pulsar log directory
      file:
        path: /var/log/pulsar
        state: directory
        owner: "{{ pulsar_user }}"
        group: "{{ pulsar_group }}"
        mode: '0755'

    # Deploy server.ini configuration from template
    - name: Copy default Pulsar configuration
      template:
        src: server.ini.j2
        dest: "{{ pulsar_install_dir }}/server.ini"
        owner: "{{ pulsar_user }}"
        group: "{{ pulsar_group }}"
        mode: '0644'

    # Deploy app.yml configuration from template
    - name: Copy default Pulsar app configuration
      template:
        src: app.yml.j2
        dest: "{{ pulsar_install_dir }}/app.yml"
        owner: "{{ pulsar_user }}"
        group: "{{ pulsar_group }}"
        mode: '0644'

    # Deploy systemd service file for Pulsar
    - name: Create Pulsar service file
      template:
        src: pulsar.service.j2
        dest: /etc/systemd/system/pulsar.service
        owner: root
        group: root
        mode: '0644'
      notify:
        - Restart Pulsar

    # Enable and start Pulsar service
    - name: Enable Pulsar service
      systemd:
        name: pulsar
        enabled: true
        state: started

  handlers:
    # Handler to restart Pulsar service when configuration changes
    - name: Restart Pulsar
      systemd:
        name: pulsar
        state: restarted